# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: omniauth-garmin 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "omniauth-garmin".freeze
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Naveed Ahmad".freeze]
  s.description = "OmniAuth strategy for Garmin".freeze
  s.email = "naveedahmada036@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/omniauth-garmin.rb",
    "lib/omniauth-garmin/version.rb",
    "lib/omniauth/strategies/garmin.rb",
    "omniauth-garmin.gemspec"
  ]
  s.homepage = "http://github.com/naveed-ahmad/omniauth-garmin".freeze
  s.licenses = ["MIT".freeze]
  s.summary = "OmniAuth strategy for Garmin".freeze

  s.add_runtime_dependency "omniauth-oauth", "~> 1.2"
  s.add_development_dependency("rdoc".freeze, ["~> 3.12"])
  s.add_development_dependency("bundler".freeze, ["~> 2.0.2"])
  s.add_development_dependency("juwelier".freeze, ["~> 2.4.9"])
  s.add_development_dependency("simplecov".freeze, [">= 0"])
end
